import Link from "next/link"
import { ArrowUpRight, Phone } from "lucide-react"
import { SiteFrame } from "@/components/editorial-shell"
import { siteConfig } from "@/lib/site"

const services = [
  { number: "01", name: "Residence", subtitle: "Your path to Costa Rica.", description: "Personalized coordination for individuals and families exploring Costa Rica residency pathways, including Investor, Independent Income (Rentista) and Retiree (Pensionado).", cta: "Explore Residence", href: "/residency" },
  { number: "02", name: "Real Estate", subtitle: "Find the right place in Costa Rica.", description: "Access to selected real estate opportunities across Costa Rica, including properties that may form part of a qualifying residency-by-investment strategy, subject to applicable requirements and verification.", cta: "Explore Real Estate", href: "/residency/real-estate", image: "/projects/plaza-los-mangos.png" },
  { number: "03", name: "Concierge", subtitle: "Costa Rica, thoughtfully coordinated.", description: "Personalized coordination of practical needs throughout the client journey, including transportation, accommodation, property visits, discovery experiences and selected third-party services.", cta: "Speak With a Marqués Private Advisor" },
  { number: "04", name: "Additional Services", subtitle: "The right expertise, when needed.", description: "Coordination with relevant legal, fiduciary, tax, immigration and other specialized professionals when required by the client’s objectives.", cta: "Explore Additional Services" },
  { number: "05", name: "Properties & Hotel Development", subtitle: "Real assets. Structured opportunities. Local execution.", description: "Marqués Advisory & Investments works with investors, families, developers and capital partners evaluating selected real estate, hospitality and development opportunities in Costa Rica. Our role may include opportunity sourcing, investment structuring, due diligence coordination, local counterparties, co-investment structures and execution across hospitality, commercial, industrial, residential and mixed-use real assets.", cta: "Explore Properties & Development", href: "/investments", image: "/projects/plaza-los-mangos.png", featured: true },
]

export default function ServicesPage() {
  return <SiteFrame>
    <main className="pt-40">
      <section className="border-b border-border bg-background px-5 py-20 md:px-8 md:py-28"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="mb-6 text-[10px] font-bold uppercase tracking-[0.24em] text-accent">Private Clients</p><h1 className="max-w-4xl font-serif text-5xl leading-[1.04] text-primary md:text-7xl">One Trusted Relationship for Your Costa Rica Journey.</h1></div><div className="max-w-xl"><p className="text-base leading-7 text-muted-foreground">Marqués Advisory &amp; Investments works with individuals, families and investors establishing a presence in Costa Rica through residency, real estate, selected services and investment opportunities.</p><p className="mt-5 text-base leading-7 text-muted-foreground">Our Private Client approach brings these needs together through one coordinated relationship in Costa Rica.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/contact" className="inline-flex items-center gap-2 bg-primary px-5 py-4 text-[10px] font-bold uppercase tracking-[0.14em] text-primary-foreground">Speak With a Marqués Private Advisor <ArrowUpRight size={14} /></Link><a href={siteConfig.callbackForm} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-primary px-5 py-4 text-[10px] font-bold uppercase tracking-[0.14em] text-primary">Request a Callback</a></div></div></div></section>
      <section className="px-5 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-7xl"><div className="mb-14 flex items-end justify-between gap-6"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-accent">Private client services</p><h2 className="mt-3 font-serif text-4xl text-primary md:text-5xl">A considered way forward.</h2></div><span className="hidden font-serif text-5xl text-accent/60 md:block">05</span></div><div>{services.map((service) => <article key={service.number} className={`grid gap-8 border-t border-border py-10 md:grid-cols-[100px_1fr_1fr] md:gap-12 ${service.featured ? "bg-secondary px-6 md:px-10" : ""}`}><div className="font-serif text-3xl text-accent">{service.number}</div><div>{service.image && <img src={service.image} alt="Costa Rica real estate opportunity" className="mb-6 h-56 w-full object-cover md:hidden" />}<p className="text-[10px] font-bold uppercase tracking-[0.18em] text-accent">{service.subtitle}</p><h3 className="mt-3 font-serif text-3xl text-primary md:text-4xl">{service.name}</h3>{service.image && <img src={service.image} alt="Costa Rica real estate opportunity" className="mt-7 hidden h-64 w-full object-cover md:block" />}</div><div className="flex flex-col items-start justify-between gap-7"><p className="max-w-xl text-sm leading-7 text-muted-foreground">{service.description}</p>{service.href ? <Link href={service.href} className="inline-flex items-center gap-2 border-b border-accent pb-2 text-[10px] font-bold uppercase tracking-[0.14em] text-primary">{service.cta} <ArrowUpRight size={14} /></Link> : <a href={siteConfig.callbackForm} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border-b border-accent pb-2 text-[10px] font-bold uppercase tracking-[0.14em] text-primary">{service.cta} <ArrowUpRight size={14} /></a>}</div></article>)}</div></div></section>
      <section className="bg-primary px-5 py-20 text-primary-foreground md:px-8 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-accent">Your Marqués Private Advisor</p><h2 className="mt-4 font-serif text-4xl leading-tight md:text-5xl">Your trusted point of contact in Costa Rica.</h2></div><div className="max-w-xl"><p className="text-base leading-7 text-primary-foreground/75">Your Marqués Private Advisor helps coordinate the people, opportunities and services relevant to your journey, providing one consistent point of contact based on your objectives and priorities.</p><p className="mt-12 text-[10px] font-bold uppercase tracking-[0.22em] text-accent">One relationship. Multiple workstreams.</p><p className="mt-4 text-base leading-7 text-primary-foreground/75">Depending on the client’s needs, Marqués may coordinate with relevant legal, immigration, fiduciary, real estate, development, hospitality and other specialized professionals and providers.</p></div></div></section>
      <section className="bg-secondary px-5 py-20 md:px-8 md:py-24"><div className="mx-auto flex max-w-7xl flex-col gap-8 md:flex-row md:items-center md:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-accent">Start with a conversation</p><h2 className="mt-3 max-w-2xl font-serif text-4xl text-primary md:text-5xl">The relationship begins with understanding your objectives.</h2></div><div className="flex flex-wrap gap-3"><Link href="/contact" className="inline-flex items-center gap-2 bg-primary px-5 py-4 text-[10px] font-bold uppercase tracking-[0.14em] text-primary-foreground">Speak With a Marqués Private Advisor <ArrowUpRight size={14} /></Link><a href={siteConfig.callbackForm} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-primary px-5 py-4 text-[10px] font-bold uppercase tracking-[0.14em] text-primary">Request a Callback</a></div></div></section>
    </main>
    <a href={siteConfig.callbackForm} target="_blank" rel="noreferrer" className="fixed bottom-5 right-5 z-40 inline-flex items-center gap-3 rounded-full border-4 border-primary bg-primary px-5 py-3 text-[10px] font-bold uppercase tracking-[0.12em] text-primary-foreground shadow-lg"><Phone size={17} /> Request a Callback</a>
  </SiteFrame>
}
