// Page-scoped editorial copy; shared navigation and language resolution remain unchanged.
export const frameworkCopy: Record<string, readonly [string, string, string]> = {
  "A considered perspective on context, rationale and alignment.": ["Una perspectiva analítica del contexto, la lógica y la alineación.", "Une perspective réfléchie sur le contexte, la logique et l’alignement.", "从背景、商业逻辑与契合度出发的审慎视角。"],
  "A high-level review may consider asset context, sponsor, commercial rationale, capital structure, execution, risk and alignment.": ["Una revisión general puede considerar el contexto del activo, el patrocinador, la lógica comercial, la estructura de capital, la ejecución, los riesgos y la alineación.", "Une analyse générale peut prendre en compte le contexte de l’actif, le promoteur, la logique commerciale, la structure du capital, l’exécution, les risques et l’alignement.", "高层次评估可考虑资产背景、发起方、商业逻辑、资本结构、执行条件、风险与契合度。"],
  "Considerations are shaped by the context of each opportunity.": ["Las consideraciones se adaptan al contexto de cada oportunidad.", "L’analyse tient compte du contexte propre à chaque opportunité.", "评估考量因具体机会背景而定。"],
  "Asset context": ["Contexto del activo", "Contexte de l’actif", "资产背景"],
  "Commercial rationale": ["Lógica comercial", "Logique commerciale", "商业逻辑"],
  "Sponsor context": ["Contexto del patrocinador", "Contexte du promoteur", "发起方背景"],
  "Capital structure": ["Estructura de capital", "Structure du capital", "资本结构"],
  "Execution context": ["Contexto de ejecución", "Contexte d’exécution", "执行背景"],
  "Risk and alignment": ["Riesgo y alineación", "Risques et alignement", "风险与契合度"],
  "Use": ["Uso", "Usage", "用途"],
  "Context": ["Contexto", "Contexte", "背景"],
  "Sponsor": ["Patrocinador", "Promoteur", "发起方"],
  "Objectives": ["Objetivos", "Objectifs", "目标"],
  "Risk": ["Riesgo", "Risque", "风险"],
  "Asset and commercial context.": ["Contexto del activo y lógica comercial.", "Contexte de l’actif et logique commerciale.", "资产背景与商业逻辑。"],
  "Sponsor and stakeholder alignment.": ["Patrocinador y alineación de las partes.", "Promoteur et alignement des parties prenantes.", "发起方与相关方的目标契合。"],
  "Capital structure and execution.": ["Estructura de capital y ejecución.", "Structure du capital et exécution.", "资本结构与执行。"],
  "The discussion considers the asset, its setting and the commercial rationale presented for its intended use.": ["La conversación considera el activo, su contexto y la lógica comercial planteada para el uso previsto.", "L’échange porte sur l’actif, son contexte et la logique commerciale avancée pour l’usage envisagé.", "交流会考虑资产、其所处背景及拟定用途的商业逻辑。"],
  "Sponsor context, participant objectives and areas of alignment help frame the opportunity.": ["El contexto del patrocinador, los objetivos de los participantes y los puntos de alineación ayudan a enmarcar la oportunidad.", "Le contexte du promoteur, les objectifs des participants et les points de convergence contribuent à cadrer l’opportunité.", "发起方背景、参与者目标及各方契合点有助于理解该机会。"],
  "Capital structure, execution context and relevant risks are considered at a high level.": ["La estructura de capital, el contexto de ejecución y los riesgos pertinentes se consideran a nivel general.", "La structure du capital, le contexte d’exécution et les risques pertinents sont examinés à un niveau général.", "以高层次视角考虑资本结构、执行背景及相关风险。"],
  "PRIVATE CONVERSATION": ["CONVERSACIÓN PRIVADA", "ÉCHANGE PRIVÉ", "私人交流"],
  "A private conversation about a real asset opportunity.": ["Una conversación privada sobre una oportunidad en activos reales.", "Un échange privé au sujet d’une opportunité en actifs réels.", "就实物资产机会进行私人交流。"],
  "Discuss a real asset opportunity in Costa Rica with Marqués.": ["Converse con Marqués sobre una oportunidad en activos reales en Costa Rica.", "Échangez avec Marqués au sujet d’une opportunité en actifs réels au Costa Rica.", "与 Marqués 探讨哥斯达黎加的实物资产机会。"],
  "Begin an Institutional Inquiry": ["Iniciar una consulta institucional", "Engager un échange institutionnel", "发起机构咨询"],
  "Pause framework motion": ["Pausar el movimiento del marco", "Mettre le défilement en pause", "暂停框架滚动"],
  "Resume framework motion": ["Reanudar el movimiento del marco", "Reprendre le défilement", "继续框架滚动"],
  "How Marqués Evaluates Real Asset Opportunities": ["Cómo evalúa Marqués las oportunidades en activos reales", "Comment Marqués évalue les opportunités en actifs réels", "Marqués 如何评估实物资产机会"],
  "Structured for capital. Built for execution.": ["Estructurados para el capital. Concebidos para la ejecución.", "Structurés pour le capital. Conçus pour l’exécution.", "为资本构建架构，为执行奠定基础。"],
  "We evaluate, structure and prepare real asset opportunities for disciplined investment and execution.": ["Evaluamos, estructuramos y preparamos oportunidades en activos reales para una inversión y ejecución disciplinadas.", "Nous évaluons, structurons et préparons les opportunités en actifs réels pour un investissement et une exécution rigoureux.", "我们评估、构建并准备实物资产机会，以支持审慎投资与有序执行。"],
  "The Marqués Review Framework": ["El marco de evaluación de Marqués", "Le cadre d’analyse Marqués", "Marqués 审查框架"],
  "From asset clarity to institutional readiness.": ["De la claridad del activo a la preparación institucional.", "De la compréhension de l’actif à la préparation institutionnelle.", "从资产明晰到机构准备。"],
  "We begin with the asset.": ["Comenzamos por el activo.", "Nous commençons par l’actif.", "始于资产。"],
  "Then we define the structure.": ["Luego definimos la estructura.", "Puis nous définissons la structure.", "继而明确架构。"],
  "Only then do we position the opportunity.": ["Solo entonces posicionamos la oportunidad.", "C’est alors que nous positionnons l’opportunité.", "而后定位机会。"],
  "Location": ["Ubicación", "Emplacement", "区位"],
  "Logic": ["Lógica", "Logique", "逻辑"],
  "Potential": ["Potencial", "Potentiel", "潜力"],
  "Readiness": ["Preparación", "Préparation", "准备"],
  "Alignment": ["Alineación", "Convergence", "契合"],
  "Asset": ["Activo", "Actif", "资产"],
  "Thesis": ["Tesis", "Thèse", "投资逻辑"],
  "Structure": ["Estructura", "Structure", "架构"],
  "Capital": ["Capital", "Capital", "资本"],
  "Execution": ["Ejecución", "Exécution", "执行"],
  "Monetization": ["Monetización", "Monétisation", "价值实现"],
  "Real Asset Review": ["Evaluación de activos reales", "Analyse d’actifs réels", "实物资产审查"],
  "Asset Categories": ["Categorías de activos", "Catégories d’actifs", "资产类别"],
  "From opportunity to institutional readiness.": ["De la oportunidad a la preparación institucional.", "De l’opportunité à la préparation institutionnelle.", "从机会到机构准备。"],
  "A private conversation about real assets, structuring and execution in Costa Rica.": ["Una conversación privada sobre activos reales, estructuración y ejecución en Costa Rica.", "Un échange privé sur les actifs réels, la structuration et l’exécution au Costa Rica.", "围绕哥斯达黎加实物资产、架构设计与执行的私人交流。"],
  "Discuss an Opportunity": ["Conversemos sobre una oportunidad", "Échanger sur une opportunité", "探讨机会"],
  "Contemporary architecture with natural light, timber and stone": ["Arquitectura contemporánea con luz natural, madera y piedra", "Architecture contemporaine, lumière naturelle, bois et pierre", "融入自然光、木材与石材的当代建筑"],
}
