export const opportunities = [
  {
    name: "Plaza Los Mangos",
    location: "Santa Cruz, Guanacaste, Costa Rica",
    classification: "Mixed-Use Institutional Development",
    image: "/projects/plaza-los-mangos.png",
    imageAlt: "Plaza Los Mangos mixed-use development rendering in Santa Cruz, Guanacaste",
    imagePosition: "center",
    assetClass: "Mixed-Use Real Asset Development",
    stage: "Predevelopment",
    role: "Project origination and investment structuring",
    thesis: "The current Plaza Los Mangos concept considers commercial, hospitality, residential, service-oriented retail and parking uses in a mixed-use development in Santa Cruz.",
    href: "/projects/plaza-los-mangos",
  },
  {
    name: "Décima Avenida",
    location: "El Roble, Alajuela, Costa Rica",
    classification: "Mixed-Use Opportunity · El Roble",
    image: "/projects/decima-avenida-rdr.jpg",
    imageAlt: "Décima Avenida mixed-use tower rendering in El Roble, Alajuela",
    imagePosition: "58% 18%",
    assetClass: "Mixed-Use / Real Asset Opportunity",
    stage: "Early-Stage Structuring",
    role: "Investment structuring and positioning",
    thesis: "A preliminary mixed-use real asset opportunity in the Coyol–Airport area, with a possible phased approach under consideration.",
    href: "/projects/decima-avenida",
  },
] as const
