// Page-scoped editorial copy: Spanish, French, Simplified Chinese.
export const opportunitiesCopy: Record<string, readonly [string, string, string]> = {
  "INSTITUTIONAL PIPELINE": ["OPORTUNIDADES INSTITUCIONALES EN DESARROLLO", "OPPORTUNITÉS INSTITUTIONNELLES À L’ÉTUDE", "机构级机会储备"],
  "Institutional Opportunities": ["Oportunidades institucionales", "Opportunités institutionnelles", "机构级机会"],
  "Selected Opportunities": ["Oportunidades seleccionadas", "Opportunités sélectionnées", "精选机会"],
  "Selected real asset opportunities in Costa Rica under origination, structuring or capital-readiness review.": [
    "Oportunidades seleccionadas en activos reales en Costa Rica, en etapas de originación, estructuración o revisión de su preparación para capital.",
    "Des opportunités sélectionnées en actifs réels au Costa Rica, en phase d’identification, de structuration ou d’examen de leur préparation au capital.",
    "哥斯达黎加精选实物资产机会，正处于机会发掘、架构设计或资本就绪审查阶段。",
  ],
  "Santa Cruz, Guanacaste, Costa Rica": ["Santa Cruz, Guanacaste, Costa Rica", "Santa Cruz, Guanacaste, Costa Rica", "哥斯达黎加瓜纳卡斯特省圣克鲁斯"],
  "El Roble, Alajuela, Costa Rica": ["El Roble, Alajuela, Costa Rica", "El Roble, Alajuela, Costa Rica", "哥斯达黎加阿拉胡埃拉省埃尔罗布莱"],
  "Mixed-Use Institutional Development": ["Desarrollo institucional de uso mixto", "Développement à usage mixte à vocation institutionnelle", "机构级综合用途开发项目"],
  "Coyol–Airport Growth Corridor": ["Corredor de crecimiento Coyol–Aeropuerto", "Corridor de croissance Coyol–Aéroport", "Coyol–机场增长走廊"],
  "Plaza Los Mangos mixed-use development rendering in Santa Cruz, Guanacaste": ["Imagen del desarrollo de uso mixto Plaza Los Mangos en Santa Cruz, Guanacaste", "Vue du développement à usage mixte Plaza Los Mangos à Santa Cruz, Guanacaste", "瓜纳卡斯特省圣克鲁斯 Plaza Los Mangos 综合用途开发效果图"],
  "Décima Avenida mixed-use tower rendering in El Roble, Alajuela": ["Imagen de la torre de uso mixto Décima Avenida en El Roble, Alajuela", "Vue de la tour à usage mixte Décima Avenida à El Roble, Alajuela", "阿拉胡埃拉省埃尔罗布莱 Décima Avenida 综合用途塔楼效果图"],
  "A mixed-use real asset opportunity currently in structuring, designed to integrate commercial, hospitality, residential, service-oriented retail and parking uses within a single institutional development framework.": [
    "Una oportunidad de uso mixto en activos reales actualmente en estructuración, concebida para integrar usos comerciales, hoteleros, residenciales, comercio orientado a servicios y estacionamientos dentro de un único marco de desarrollo institucional.",
    "Une opportunité en actifs réels à usage mixte actuellement en cours de structuration, conçue pour réunir activités commerciales, hôtellerie, logements, commerces de services et stationnement dans un cadre de développement institutionnel intégré.",
    "一项目前处于架构设计阶段的综合用途实物资产机会，旨在统一的机构级开发框架下整合商业、酒店、住宅、服务型零售及停车用途。",
  ],
  "A preliminary mixed-use real asset opportunity under evaluation in the Coyol–Airport ecosystem, with potential for phased positioning subject to diligence, documentation and institutional review.": [
    "Una oportunidad preliminar de uso mixto en activos reales bajo evaluación en el ecosistema Coyol–Aeropuerto, con potencial de posicionamiento por fases, sujeta a diligencia, documentación y revisión institucional.",
    "Une opportunité préliminaire en actifs réels à usage mixte, en cours d’évaluation dans l’écosystème Coyol–Aéroport, présentant un potentiel de positionnement par phases sous réserve de diligence, de documentation et d’examen institutionnel.",
    "一项位于 Coyol–机场生态圈、正在评估中的初步综合用途实物资产机会，具有分阶段定位的潜力，须经尽职调查、文件准备及机构审查。",
  ],
  "Asset Class": ["Clase de activo", "Classe d’actifs", "资产类别"],
  "Mixed-Use Real Asset Development": ["Desarrollo de activos reales de uso mixto", "Développement d’actifs réels à usage mixte", "综合用途实物资产开发"],
  "Mixed-Use / Real Asset Opportunity": ["Uso mixto / Oportunidad en activos reales", "Usage mixte / Opportunité en actifs réels", "综合用途 / 实物资产机会"],
  "Pipeline Stage": ["Etapa de preparación", "Stade de préparation", "准备阶段"],
  "Predevelopment / Capital Readiness": ["Predesarrollo / Preparación para capital", "Pré-développement / Préparation au capital", "前期开发 / 资本就绪准备"],
  "Origination / Under Structuring": ["Originación / En estructuración", "Identification / En cours de structuration", "机会发掘 / 架构设计中"],
  "MA&I Role": ["Rol de MA&I", "Rôle de MA&I", "MA&I 的角色"],
  "Origination, structuring, capital readiness and institutional positioning": ["Originación, estructuración, preparación para capital y posicionamiento institucional", "Identification, structuration, préparation au capital et positionnement institutionnel", "机会发掘、架构设计、资本就绪准备及机构定位"],
  "Thesis development, structuring review and strategic positioning": ["Desarrollo de tesis, revisión de estructuración y posicionamiento estratégico", "Développement de la thèse, examen de la structuration et positionnement stratégique", "投资逻辑构建、架构审查及战略定位"],
  "Review Basis": ["Base de revisión", "Base d’examen", "审查基础"],
  "Subject to diligence and institutional review": ["Sujeto a diligencia y revisión institucional", "Sous réserve de diligence et d’examen institutionnel", "须经尽职调查及机构审查"],
  "View Institutional Overview": ["Ver presentación institucional", "Consulter la présentation institutionnelle", "查看机构概览"],
  "Confidential Investment Materials": ["Documentación confidencial de inversión", "Documentation d’investissement confidentielle", "保密投资资料"],
  "Detailed investment information is available to qualified private and institutional counterparties following appropriate review and execution of a confidentiality agreement.": [
    "La información detallada de inversión está disponible para contrapartes privadas e institucionales calificadas, tras la revisión correspondiente y la firma de un acuerdo de confidencialidad.",
    "Les informations détaillées relatives aux investissements sont accessibles aux contreparties privées et institutionnelles qualifiées, après un examen approprié et la signature d’un accord de confidentialité.",
    "符合条件的私人及机构合作方，在完成适当审查并签署保密协议后，可获取详细投资信息。",
  ],
  "Request Institutional Access": ["Solicitar acceso institucional", "Demander un accès institutionnel", "申请机构资料访问"],
}
