// Page-scoped editorial copy: Spanish, French, Simplified Chinese.
export const opportunitiesCopy: Record<string, readonly [string, string, string]> = {
  "SELECTED OPPORTUNITIES": ["OPORTUNIDADES SELECCIONADAS", "OPPORTUNITÉS SÉLECTIONNÉES", "精选机会"],
  "INSTITUTIONAL PIPELINE": ["OPORTUNIDADES INSTITUCIONALES EN DESARROLLO", "OPPORTUNITÉS INSTITUTIONNELLES À L’ÉTUDE", "机构级机会储备"],
  "Institutional Opportunities": ["Oportunidades institucionales", "Opportunités institutionnelles", "机构级机会"],
  "Selected Opportunities": ["Oportunidades seleccionadas", "Opportunités sélectionnées", "精选机会"],
  "Selected real asset opportunities in Costa Rica, presented with context on location, development concept and current stage.": [
    "Oportunidades seleccionadas en activos reales en Costa Rica, con información sobre su ubicación, concepto de desarrollo y etapa actual.",
    "Des opportunités sélectionnées en actifs réels au Costa Rica, présentées avec des informations sur leur emplacement, leur concept de développement et leur stade actuel.",
    "精选哥斯达黎加实物资产机会，附有区位、开发概念及当前阶段的背景信息。",
  ],
  "Santa Cruz, Guanacaste, Costa Rica": ["Santa Cruz, Guanacaste, Costa Rica", "Santa Cruz, Guanacaste, Costa Rica", "哥斯达黎加瓜纳卡斯特省圣克鲁斯"],
  "El Roble, Alajuela, Costa Rica": ["El Roble, Alajuela, Costa Rica", "El Roble, Alajuela, Costa Rica", "哥斯达黎加阿拉胡埃拉省埃尔罗布莱"],
  "Mixed-Use Institutional Development": ["Desarrollo de uso mixto", "Développement à usage mixte", "综合用途开发项目"],
  "Mixed-Use Opportunity · El Roble": ["Oportunidad de uso mixto · El Roble", "Opportunité à usage mixte · El Roble", "综合用途机会 · El Roble"],
  "Plaza Los Mangos mixed-use development rendering in Santa Cruz, Guanacaste": ["Imagen del desarrollo de uso mixto Plaza Los Mangos en Santa Cruz, Guanacaste", "Vue du développement à usage mixte Plaza Los Mangos à Santa Cruz, Guanacaste", "瓜纳卡斯特省圣克鲁斯 Plaza Los Mangos 综合用途开发效果图"],
  "Décima Avenida mixed-use tower rendering in El Roble, Alajuela": ["Imagen de la torre de uso mixto Décima Avenida en El Roble, Alajuela", "Vue de la tour à usage mixte Décima Avenida à El Roble, Alajuela", "阿拉胡埃拉省埃尔罗布莱 Décima Avenida 综合用途塔楼效果图"],
  "The current Plaza Los Mangos concept considers commercial, hospitality, residential, service-oriented retail and parking uses in a mixed-use development in Santa Cruz.": [
    "El concepto actual de Plaza Los Mangos contempla usos comerciales, hoteleros, residenciales, de comercio orientado a servicios y estacionamiento en un desarrollo de uso mixto en Santa Cruz.",
    "Le concept actuel de Plaza Los Mangos envisage des usages commerciaux, hôteliers, résidentiels, des commerces de services et du stationnement dans un développement mixte à Santa Cruz.",
    "Plaza Los Mangos 当前概念考虑在 Santa Cruz 的综合用途开发中设置商业、酒店、住宅、服务型零售及停车用途。",
  ],
  "A preliminary mixed-use real asset opportunity in the Coyol–Airport area, with a possible phased approach under consideration.": [
    "Una oportunidad preliminar de uso mixto en activos reales en la zona Coyol–Aeropuerto, donde se considera un posible enfoque por fases.",
    "Une opportunité préliminaire d’actif réel à usage mixte dans la zone Coyol–Aéroport, où une approche par phases est à l’étude.",
    "Coyol–机场区域的一项初步综合用途实物资产机会，目前正在考虑分阶段方案。",
  ],
  "Asset Class": ["Clase de activo", "Classe d’actifs", "资产类别"],
  "Mixed-Use Real Asset Development": ["Desarrollo de activos reales de uso mixto", "Développement d’actifs réels à usage mixte", "综合用途实物资产开发"],
  "Mixed-Use / Real Asset Opportunity": ["Uso mixto / Oportunidad en activos reales", "Usage mixte / Opportunité en actifs réels", "综合用途 / 实物资产机会"],
  "Project Stage": ["Etapa del proyecto", "Stade du projet", "项目阶段"],
  "Predevelopment": ["Predesarrollo", "Pré-développement", "前期开发"],
  "Early-Stage Structuring": ["Estructuración inicial", "Structuration préliminaire", "早期结构规划"],
  "MA&I Role": ["Rol de MA&I", "Rôle de MA&I", "MA&I 的角色"],
  "Project origination and investment structuring": ["Originación del proyecto y estructuración de inversión", "Origination du projet et structuration de l’investissement", "项目发起与投资结构规划"],
  "Investment structuring and positioning": ["Estructuración y posicionamiento de inversión", "Structuration et positionnement de l’investissement", "投资结构规划与定位"],
  "View Institutional Overview": ["Ver presentación institucional", "Consulter la présentation institutionnelle", "查看机构概览"],
  "Confidential Investment Materials": ["Documentación confidencial de inversión", "Documentation d’investissement confidentielle", "保密投资资料"],
  "Qualified private and institutional parties may request further information, subject to confidentiality requirements.": [
    "Las partes privadas e institucionales calificadas pueden solicitar más información, sujeta a los requisitos de confidencialidad.",
    "Les parties privées et institutionnelles qualifiées peuvent demander des informations complémentaires, sous réserve des exigences de confidentialité.",
    "符合条件的私人及机构方可申请进一步信息，但须遵守保密要求。",
  ],
  "Request Institutional Access": ["Solicitar acceso institucional", "Demander un accès institutionnel", "申请机构资料访问"],
}
