import type { Metadata } from "next"
import Link from "next/link"
import { SiteHeader } from "@/components/site-header"
import { createMetadata } from "@/lib/seo"
import { siteConfig } from "@/lib/site"

export const metadata: Metadata = createMetadata({ title: "Privacy Policy", description: "Privacy Policy for Marques Advisory & Investments.", path: "/privacy" })

const sections = [
  { title: "1. Responsible Entity", paragraphs: [`The entity responsible for personal information collected through MA&I is ${siteConfig.legalEntity}, operating as ${siteConfig.name}, corporate identification number ${siteConfig.corporateId}, with legal address at ${siteConfig.legalAddress}.`, "Our processing of personal information is governed principally by Costa Rica’s Law No. 8968, Protection of the Person in the Processing of Personal Data, its applicable regulations, and other laws that may apply to a particular processing activity. Where another data protection law is legally applicable because of its territorial scope, MA&I will address the requirements applicable to that specific processing activity."] },
  { title: "2. Information We Collect", paragraphs: ["Depending on how you interact with MA&I, we may collect:"], bullets: ["Salutation, first and last name", "Telephone number and e-mail address", "Country of citizenship and country of residence", "Preferred communication method", "Program, service, or opportunity of interest", "The nature of your enquiry and information you voluntarily provide", "Communications with MA&I and marketing preferences", "Limited technical information such as IP address, browser or device information, access time, pages accessed, and diagnostic or security information"] },
  { title: "3. Information You Should Not Submit Through General Enquiry", paragraphs: ["The General Enquiry Form is intended for initial enquiries and is not designed for highly sensitive or confidential documentation. Unless specifically requested through an appropriate MA&I process, please do not submit:"], bullets: ["Passport or identification documents", "Bank statements, banking credentials, or detailed financial information", "Passwords or authentication credentials", "Medical information, criminal records, or biometric information", "Other sensitive personal information"] },
  { title: "4. How We Use Personal Information", paragraphs: ["We may process personal information to receive and respond to enquiries; identify the program, service, or opportunity in which you are interested; coordinate consultations; communicate through your preferred method; evaluate a potential or existing professional relationship; maintain records; operate and protect our systems; prevent misuse; protect legitimate legal interests; and comply with applicable legal, regulatory, judicial, accounting, tax, compliance, or professional obligations.", "MA&I will not intentionally use personal information for a materially incompatible purpose without providing additional notice or obtaining any authorization required by applicable law."] },
  { title: "5. Consent and Required Information", paragraphs: ["Where consent is required, MA&I will seek consent that is express, informed, specific, and capable of being evidenced in written or electronic form. Mandatory fields are necessary to receive or respond to the corresponding request; optional fields may be left blank.", "Certain information may become mandatory depending on your selections. For example, a telephone number may be required when you request contact by telephone or WhatsApp. Where processing is based on consent, it may be withdrawn in accordance with applicable law without retroactively invalidating lawful processing performed before withdrawal."] },
  { title: "6. Marketing Communications", paragraphs: ["Marketing consent is separate, optional, and is not required to submit an enquiry or request a consultation. If you elect to receive communications, MA&I may send selected information about Costa Rica residence programs, real estate, investment or development opportunities, insights, events, and related activities.", "You may unsubscribe or withdraw marketing consent at any time and without charge. Withdrawal does not prevent MA&I from contacting you about an active enquiry, requested service, existing relationship, transaction, or legal obligation."] },
  { title: "7. Service Providers", paragraphs: ["MA&I may use technology and professional service providers for website hosting, form processing, e-mail and communications, cloud infrastructure and storage, cybersecurity, technical support, relationship management, and professional administration. These providers may process information on behalf of MA&I only to the extent reasonably necessary to perform the relevant service.", "Where applicable, MA&I will seek appropriate confidentiality, contractual, organizational, and security protections. A service provider acting on our behalf is distinct from an independent third party processing information for its own purposes."] },
  { title: "8. Disclosure to Independent Third Parties", paragraphs: ["Submitting an enquiry does not constitute blanket authorization to disclose your information to independent third parties. A future engagement may involve an independent legal, immigration, tax, fiduciary, banking, financial, real estate, investment, development, or other professional adviser or counterparty.", "Where disclosure requires your consent, MA&I will obtain the appropriate authorization before transfer, except where disclosure is required or otherwise permitted by applicable law, judicial order, or competent authority. An independent recipient may process information under its own privacy obligations and policies."] },
  { title: "9. International Processing", paragraphs: ["MA&I operates from Costa Rica and serves an international clientele. Some technology or service providers may operate infrastructure outside Costa Rica. Where information is processed internationally on behalf of MA&I, we will seek appropriate safeguards considering the nature of the information and applicable legal requirements. Where a transfer to an independent recipient requires consent, MA&I will obtain the required authorization unless applicable law provides otherwise."] },
  { title: "10. Data Security and Confidentiality", paragraphs: ["MA&I uses reasonable administrative, organizational, physical, and technical safeguards designed to protect personal information against unauthorized access, misuse, alteration, disclosure, loss, or destruction. Access is intended to be restricted to authorized persons and systems that reasonably require it.", "No internet transmission, communication, or storage system can be guaranteed completely secure. If an incident affecting personal information occurs, MA&I will assess and address it and undertake notifications or other measures required by applicable law."] },
  { title: "11. Data Retention", paragraphs: ["MA&I retains personal information only as long as reasonably necessary for the purpose for which it was collected and for applicable legal, contractual, regulatory, accounting, tax, compliance, dispute-resolution, or professional requirements. Enquiry information that does not progress may be deleted or anonymized when no longer reasonably necessary. Ongoing client, contractual, transaction, compliance, or professional relationships may be subject to different retention requirements."] },
  { title: "12. Your Rights", paragraphs: ["Subject to applicable law, you may request access to personal information concerning you; correction or updating of inaccurate or incomplete information; deletion where legally appropriate; information about processing purposes; exercise of rights concerning transfers or disclosures; and withdrawal of consent where processing is based on consent.", "MA&I may take reasonable steps to verify the identity and authority of the person submitting a request. Requests will be handled within the periods and conditions established by applicable law."] },
  { title: "13. Cookies and Analytics", paragraphs: ["MA&I may use privacy-conscious technologies to understand website performance and use. Where cookies or similar technologies are implemented, MA&I will provide any notice or consent mechanism required by applicable law. Additional information about technologies actually implemented may be provided in a Cookie Policy or Cookie Notice."] },
  { title: "14. Third-Party Websites", paragraphs: ["Our website may link to independently operated websites or services. MA&I does not control their privacy, security, content, or data-processing practices. Review the applicable privacy information before providing personal information directly to those parties."] },
  { title: "15. Minors", paragraphs: ["The MA&I website, General Enquiry Form, and private-client advisory services are intended for adults and are not directed to children or minors. MA&I does not intentionally solicit personal information from minors through its General Enquiry Form."] },
  { title: "16. Changes to This Privacy Policy", paragraphs: ["We may update this policy to reflect changes in services, technologies, processing practices, legal requirements, or privacy and security practices. The current version will display its effective or last-updated date. Publication of an amended policy does not replace any additional consent legally required for a new purpose."] },
  { title: "17. Contact", paragraphs: [`Privacy requests and questions may be sent to ${siteConfig.legalEmail}. The responsible entity is ${siteConfig.legalEntity}, operating as ${siteConfig.name}, corporate identification number ${siteConfig.corporateId}, at ${siteConfig.legalAddress}.`] },
]

export default function PrivacyPage() {
  return <main className="min-h-screen bg-[#f5f0e7] text-[#0b1b2a]"><SiteHeader /><header className="bg-[#091725] px-6 pb-20 pt-40 text-white md:px-10"><div className="mx-auto max-w-5xl"><p className="mb-5 text-[11px] font-semibold uppercase tracking-[.2em] text-[#d7b779]">Legal</p><h1 className="font-serif text-[clamp(3rem,6vw,5.8rem)] leading-none tracking-[-.04em]">Privacy Policy</h1><p className="mt-6 text-sm text-white/55">Effective and last updated: 25 August 2026</p></div></header><article className="px-6 py-16 md:px-10 md:py-20"><div className="mx-auto max-w-5xl"><p className="max-w-3xl text-lg leading-8 text-[#45525d]">{siteConfig.name} is operated by {siteConfig.legalEntity}. This policy explains how we collect, use, protect, retain, and disclose personal information obtained through marquescr.com, our enquiry forms, and related communications.</p><div className="mt-12 divide-y divide-[#b89a65]/30 border-y border-[#b89a65]/30">{sections.map((section) => <section key={section.title} className="grid gap-5 py-8 md:grid-cols-[.34fr_.66fr] md:py-10"><h2 className="font-serif text-2xl">{section.title}</h2><div className="space-y-4 text-sm leading-7 text-[#53606b]">{section.paragraphs.map((p) => <p key={p}>{p}</p>)}{"bullets" in section && section.bullets ? <ul className="list-disc space-y-2 pl-5">{section.bullets.map((item) => <li key={item}>{item}</li>)}</ul> : null}{section.title === "12. Your Rights" || section.title === "17. Contact" ? <a href={`mailto:${siteConfig.legalEmail}`} className="inline-flex border-b border-[#96733b] font-semibold text-[#765624]">{siteConfig.legalEmail}</a> : null}</div></section>)}</div><Link href="/" className="mt-10 inline-flex min-h-11 items-center border-b border-[#96733b] py-2 text-sm font-semibold text-[#765624]">Return to Marques Advisory & Investments</Link></div></article></main>
}
