'use client'

import { FormEvent, useState } from 'react'
import { ArrowUpRight, Check, ChevronRight, Download, Globe2, Landmark, Mail, Menu, ShieldCheck, X } from 'lucide-react'

const assets = [
  { title: 'Plaza Los Mangos', location: 'Santa Ana, Costa Rica', amount: 'From $200,000', image: '/projects/plaza-los-mangos.png' },
  { title: 'Décima Avenida', location: 'San José, Costa Rica', amount: 'From $250,000', image: '/professional-man.png' },
  { title: 'Tropical Development Sites', location: 'Guanacaste, Costa Rica', amount: 'By private brief', image: '/woman-founder.png' },
]

function Logo() {
  return <a href="#top" className="flex items-center gap-3" aria-label="Márquez Advisory home"><span className="flex h-9 w-9 items-center justify-center border border-accent text-lg font-serif text-accent">M</span><span className="max-w-32 text-[11px] font-medium uppercase leading-tight tracking-[0.16em] text-foreground">Márquez<br />Advisory & Investments</span></a>
}

function Header({ active, setActive }: { active: 'resident' | 'invest'; setActive: (value: 'resident' | 'invest') => void }) {
  const [open, setOpen] = useState(false)
  return <header className="sticky top-0 z-40 border-b border-border bg-background/95 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4 md:px-8"><Logo /><nav className="hidden items-center gap-1 rounded-full border border-border bg-card p-1 md:flex" aria-label="Primary"><button onClick={() => setActive('resident')} className={`rounded-full px-4 py-2 text-[11px] font-semibold uppercase tracking-[0.1em] transition-all ${active === 'resident' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground'}`}>Residency in Costa Rica</button><button onClick={() => setActive('invest')} className={`rounded-full px-4 py-2 text-[11px] font-semibold uppercase tracking-[0.1em] transition-all ${active === 'invest' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground'}`}>Investments</button></nav><a href="#contact" className="hidden items-center gap-2 border border-primary px-4 py-2 text-[11px] font-semibold uppercase tracking-[0.12em] text-primary transition-all hover:bg-primary hover:text-primary-foreground sm:flex">Contact Advisory <ArrowUpRight size={14} /></a><button className="p-2 text-primary md:hidden" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X size={21} /> : <Menu size={21} />}</button></div>{open && <div className="flex flex-col gap-2 border-t border-border px-5 pb-5 pt-3 md:hidden"><button onClick={() => { setActive('resident'); setOpen(false) }} className="px-2 py-3 text-left text-sm uppercase tracking-wider">Residency in Costa Rica</button><button onClick={() => { setActive('invest'); setOpen(false) }} className="px-2 py-3 text-left text-sm uppercase tracking-wider">Investments</button><a href="#contact" onClick={() => setOpen(false)} className="mt-2 bg-primary px-4 py-3 text-center text-xs font-semibold uppercase tracking-wider text-primary-foreground">Contact Advisory</a></div>}</header>
}

function ContactForm({ asset = '' }: { asset?: string }) {
  const [sent, setSent] = useState(false)
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true) }
  if (sent) return <div className="flex min-h-52 flex-col items-center justify-center gap-4 text-center"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-accent text-accent-foreground"><Check size={22} /></span><h3 className="font-serif text-2xl">Thank you.</h3><p className="max-w-sm text-sm leading-6 text-muted-foreground">Your inquiry is with our advisory team. We will be in touch shortly.</p></div>
  return <form onSubmit={submit} className="grid gap-4"><input type="hidden" name="asset" value={asset} /><label className="grid gap-2 text-xs font-semibold uppercase tracking-widest">Full name<input required name="name" className="border border-border bg-background px-4 py-3 text-sm font-normal normal-case tracking-normal outline-none ring-accent transition-all focus:ring-1" placeholder="Your name" /></label><label className="grid gap-2 text-xs font-semibold uppercase tracking-widest">Email address<input required type="email" name="email" className="border border-border bg-background px-4 py-3 text-sm font-normal normal-case tracking-normal outline-none ring-accent transition-all focus:ring-1" placeholder="you@company.com" /></label><label className="grid gap-2 text-xs font-semibold uppercase tracking-widest">How can we help?<textarea name="message" rows={3} defaultValue={asset ? `I am interested in ${asset}.` : ''} className="resize-none border border-border bg-background px-4 py-3 text-sm font-normal normal-case tracking-normal outline-none ring-accent transition-all focus:ring-1" placeholder="Tell us a little about your goals" /></label><button className="flex items-center justify-center gap-2 bg-primary px-5 py-3.5 text-xs font-bold uppercase tracking-[0.14em] text-primary-foreground transition-all hover:bg-accent hover:text-accent-foreground">Begin a conversation <ArrowUpRight size={15} /></button></form>
}

function Hero({ setActive }: { setActive: (value: 'resident' | 'invest') => void }) { return <section id="top" className="border-b border-border"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 md:grid-cols-[1.1fr_0.9fr] md:px-8 md:py-28"><div className="flex flex-col justify-center"><p className="mb-6 flex items-center gap-3 text-[11px] font-semibold uppercase tracking-[0.2em] text-accent"><span className="h-px w-8 bg-accent" /> Costa Rica · Private Advisory</p><h1 className="max-w-3xl font-serif text-5xl leading-[1.03] text-primary md:text-7xl">A considered path to <em className="font-normal text-accent">belonging</em> and ownership.</h1><p className="mt-7 max-w-xl text-base leading-7 text-muted-foreground md:text-lg">Márquez Advisory & Investments connects global mobility with carefully structured real assets—helping you make Costa Rica part of your next chapter.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={() => setActive('resident')} className="flex items-center justify-center gap-3 bg-primary px-6 py-4 text-xs font-bold uppercase tracking-[0.12em] text-primary-foreground transition-all hover:bg-accent hover:text-accent-foreground">Explore residency <ChevronRight size={16} /></button><button onClick={() => setActive('invest')} className="flex items-center justify-center gap-3 border border-primary px-6 py-4 text-xs font-bold uppercase tracking-[0.12em] text-primary transition-all hover:bg-primary hover:text-primary-foreground">View investments <ChevronRight size={16} /></button></div></div><div className="relative min-h-[360px] overflow-hidden bg-primary md:min-h-[500px]"><img src="/projects/plaza-los-mangos.png" alt="Costa Rican real estate opportunity" className="h-full w-full object-cover opacity-75" /><div className="absolute inset-0 bg-primary/20" /><div className="absolute bottom-0 left-0 right-0 bg-primary/90 p-6 text-primary-foreground"><p className="mb-2 text-[10px] uppercase tracking-[0.18em] text-accent">The Márquez perspective</p><p className="font-serif text-xl leading-snug">Clarity for decisions that shape a life—and a legacy.</p></div></div></div></section> }

function ResidentView() { return <div className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-24"><div className="grid gap-12 md:grid-cols-[0.85fr_1.15fr] md:gap-20"><div><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-accent">Global mobility</p><h2 className="mt-4 font-serif text-4xl leading-tight text-primary md:text-5xl">Make Costa Rica your <em className="font-normal">home base.</em></h2><p className="mt-6 text-sm leading-7 text-muted-foreground">Costa Rica’s investor residency program offers a practical path for individuals and families seeking security, quality of life and a new operating base in the Americas.</p><div className="mt-8 grid gap-5 border-t border-border pt-7"><div className="flex gap-4"><ShieldCheck className="shrink-0 text-accent" size={22} /><div><h3 className="font-semibold text-primary">Security by design</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">A stable jurisdiction and a thoughtful framework for your family and capital.</p></div></div><div className="flex gap-4"><Globe2 className="shrink-0 text-accent" size={22} /><div><h3 className="font-semibold text-primary">A life well-lived</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">Nature, healthcare, education and a globally connected lifestyle.</p></div></div><div className="flex gap-4"><Landmark className="shrink-0 text-accent" size={22} /><div><h3 className="font-semibold text-primary">Investment-led</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">Explore eligible real estate while building a meaningful presence.</p></div></div></div></div><div className="bg-secondary p-6 md:p-10"><div className="mb-8 flex items-start justify-between gap-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-accent">Start with clarity</p><h2 className="mt-3 font-serif text-3xl text-primary">Download the program brochure</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">A concise overview of requirements, process and what to expect.</p></div><Download className="shrink-0 text-accent" size={24} /></div><ContactForm /></div></div><div id="contact" className="mt-20 grid gap-8 border-t border-border pt-12 md:grid-cols-2"><div><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-accent">Personal advisory</p><h2 className="mt-3 font-serif text-3xl text-primary">Not sure where to begin?</h2><p className="mt-4 max-w-md text-sm leading-7 text-muted-foreground">You do not need to have a property selected. We can map the right path across residency, real estate and your wider objectives.</p></div><ContactForm /></div></div> }

function InvestView() { const [selected, setSelected] = useState(''); return <div className="mx-auto max-w-7xl px-5 py-16 md:px-8 md:py-24"><div className="flex flex-col justify-between gap-6 border-b border-border pb-10 md:flex-row md:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-accent">Private opportunities</p><h2 className="mt-4 max-w-2xl font-serif text-4xl leading-tight text-primary md:text-5xl">Real assets, <em className="font-normal">properly positioned.</em></h2></div><p className="max-w-sm text-sm leading-7 text-muted-foreground">We structure off-market opportunities and investment-ready projects for discerning capital partners seeking durable value in Costa Rica.</p></div><div className="mt-10 grid gap-6 md:grid-cols-3">{assets.map((asset) => <article key={asset.title} className="group border border-border bg-card"><div className="relative aspect-[4/3] overflow-hidden bg-muted"><img src={asset.image} alt={asset.title} className="h-full w-full object-cover transition-all duration-500 group-hover:scale-105" /><span className="absolute left-3 top-3 bg-accent px-3 py-1.5 text-[10px] font-bold uppercase tracking-widest text-accent-foreground">Residency eligible</span></div><div className="p-5"><p className="text-[10px] uppercase tracking-widest text-accent">{asset.location}</p><h3 className="mt-2 font-serif text-2xl text-primary">{asset.title}</h3><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><span className="text-sm text-muted-foreground">{asset.amount}</span><button onClick={() => setSelected(asset.title)} className="flex items-center gap-1 text-[10px] font-bold uppercase tracking-widest text-primary transition-all hover:text-accent">Inquire <ArrowUpRight size={14} /></button></div></div></article>)}</div><div className="mt-16 grid gap-8 border border-accent/40 bg-secondary p-6 md:grid-cols-[1fr_0.9fr] md:p-10"><div><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-accent">Asset inquiry</p><h2 className="mt-3 font-serif text-3xl text-primary">A private conversation is the first step.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Tell us what you are looking for and we will share the relevant details, availability and next steps.</p></div><ContactForm asset={selected} /></div></div> }

export default function Home() { const [active, setActive] = useState<'resident' | 'invest'>('resident'); return <main className="min-h-screen bg-background text-foreground"><Header active={active} setActive={setActive} /><Hero setActive={setActive} />{active === 'resident' ? <ResidentView /> : <InvestView />}<footer className="border-t border-border bg-primary px-5 py-12 text-primary-foreground md:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-10 md:flex-row md:items-end md:justify-between"><div><Logo /><p className="mt-5 max-w-xs text-xs leading-6 text-primary-foreground/60">Independent advisory for global mobility and real assets in Costa Rica.</p></div><div className="flex flex-col gap-3 text-sm text-primary-foreground/70 md:items-end"><a href="mailto:advisory@marquezadvisory.com" className="flex items-center gap-2 hover:text-accent"><Mail size={15} /> advisory@marquezadvisory.com</a><p className="text-xs text-primary-foreground/50">© 2026 Márquez Advisory & Investments · Terms & Privacy</p></div></div></footer></main> }
