"use client"
import { FormEvent, useState } from "react"
import { Check } from "lucide-react"
import Link from "next/link"

export function EnquiryForm({ type = "general" }: { type?: string }) {
  const [sent, setSent] = useState(false)
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setSent(true) }
  if (sent) return <div className="border border-accent bg-secondary p-10 text-center"><Check className="mx-auto text-accent" size={28} /><h3 className="mt-4 font-serif text-3xl text-primary">Thank you.</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Your enquiry has been received. Our advisory team will respond shortly.</p></div>
  return <form onSubmit={submit} className="grid gap-5"><input type="hidden" name="enquiry_type" value={type} /><label className="grid gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-primary">Full name<input required name="name" className="border border-border bg-background px-4 py-3 text-sm font-normal normal-case tracking-normal outline-none focus:border-accent" /></label><label className="grid gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-primary">Email address<input required type="email" name="email" className="border border-border bg-background px-4 py-3 text-sm font-normal normal-case tracking-normal outline-none focus:border-accent" /></label><label className="grid gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-primary">Telephone <span className="font-normal normal-case tracking-normal text-muted-foreground">(optional)</span><input type="tel" name="telephone" className="border border-border bg-background px-4 py-3 text-sm font-normal normal-case tracking-normal outline-none focus:border-accent" /></label><label className="grid gap-2 text-[10px] font-bold uppercase tracking-[0.16em] text-primary">Tell us about your goals<textarea required name="message" rows={5} className="resize-y border border-border bg-background px-4 py-3 text-sm font-normal normal-case tracking-normal outline-none focus:border-accent" /></label><label className="flex items-start gap-3 text-xs leading-5 text-muted-foreground"><input required type="checkbox" className="mt-1 accent-accent" /> I agree to the <Link href="/privacy" className="text-primary underline">privacy policy</Link> and consent to being contacted about this enquiry.</label><button className="bg-primary px-6 py-4 text-[10px] font-bold uppercase tracking-[0.15em] text-primary-foreground hover:bg-accent hover:text-accent-foreground">Submit enquiry</button><p className="text-[11px] leading-5 text-muted-foreground">Your information is used only to respond to this enquiry. Submission is prepared for connection to our advisory CRM.</p></form>
}
