export type Locale = "en" | "es" | "fr" | "zh"

export const localeLabels: Record<Locale, string> = {
  en: "EN",
  es: "ES",
  fr: "FR",
  zh: "中文",
}

export const factSheetByLocale: Record<Locale, string> = {
  en: "/factsheets/costa-rica-residence-en.pdf",
  es: "/factsheets/costa-rica-residence-es.pdf",
  fr: "/factsheets/costa-rica-residence-fr.pdf",
  zh: "/factsheets/costa-rica-residence-zh.pdf",
}

export const homeContent = {
  en: {
    nav: {
      program: "Program",
      costaRica: "Costa Rica",
      costaRicaDetail: "Residence Program",
      advisory: "Residence Advisory",
      investor: "Investor",
      pensioner: "Pensioner",
      rentier: "Rentier",
      investments: "Investments",
      experience: "The MA&I Experience",
      consultation: "Private Consultation",
      menu: "Open menu",
    },
    landing: {
      eyebrow: "Marques Advisory & Investments",
      title: "Residence advisory. Real-asset opportunities. One Costa Rica platform.",
      body: "We advise globally mobile families on Costa Rica residence pathways and structure selected real-estate and real-asset opportunities.",
      choose: "Choose your next step",
      advisoryLabel: "Advisory",
      advisoryTitle: "Become a Resident in Costa Rica",
      advisoryDetail: "Investor · Pensioner · Rentier",
      investmentsLabel: "Investments",
      investmentsTitle: "Explore Investment Opportunities",
      investmentsDetail: "Real estate · Structured real assets",
    },
    hero: {
      eyebrow: "Costa Rica Residence Program",
      title: "Become a Resident in Costa Rica.",
      body: "A private, coordinated path for investors, pensioners and rentiers — managed from profile review through local execution.",
      primary: "Explore the program",
      secondary: "Begin a private consultation",
      country: "Costa Rica",
      program: "Residence Program",
      note: "One country. Three pathways. One Private Client Advisor.",
    },
    pathways: {
      kicker: "Find your pathway",
      title: "A clear decision in thirty seconds.",
      intro: "Choose the profile that best reflects your current position. Detailed evidence and government requirements are reviewed privately during the process.",
      investor: {
        title: "Investor",
        body: "For applicants who hold — or intend to make — a qualifying investment in Costa Rica.",
        existing: "I already invested",
        explore: "Explore investment options",
      },
      pensioner: {
        title: "Pensioner",
        body: "For applicants receiving a qualifying lifetime pension.",
        action: "Review this pathway",
      },
      rentier: {
        title: "Rentier",
        body: "For applicants able to demonstrate qualifying stable recurring income.",
        action: "Review this pathway",
      },
    },
    overview: {
      kicker: "Program overview",
      title: "Costa Rica, coordinated around your family.",
      body: "MA&I reviews your profile, identifies the appropriate residence route and coordinates local execution with qualified professionals. Government approval always remains with Costa Rica's immigration authority.",
      facts: [
        ["Pathways", "Investor · Pensioner · Rentier"],
        ["Service", "Private residence coordination"],
        ["Execution", "One dedicated advisory relationship"],
      ],
      factSheetTitle: "Costa Rica Residence Fact Sheet",
      factSheetBody: "A concise two-page brief designed to review and share privately with your family.",
      download: "Download fact sheet",
      share: "Share via WhatsApp",
    },
    experience: {
      kicker: "Private Client Advisory",
      title: "The experience we are designed to deliver.",
      items: [
        "I was assigned a Private Client Advisor who coordinated the process from beginning to end.",
        "With the right guidance, the process felt clear, structured and manageable.",
      ],
      note: "Service principles — not client testimonials.",
    },
    investments: {
      kicker: "Marques Investments",
      title: "Need an investment before applying?",
      body: "Selected real-estate and other investment opportunities will be introduced as they complete MA&I's internal review. If you already own an eligible asset, you can begin with Residence Advisory now.",
      status: "Investment opportunities · Coming soon",
      detail: "Private review available for residence-related investment needs.",
      action: "Discuss my position",
    },
    closing: {
      kicker: "Begin privately",
      title: "Your first step is a confidential conversation.",
      body: "Tell us where you are today. A Private Client Advisor will help identify the appropriate next step.",
      action: "Begin private consultation",
    },
    footer: {
      privacy: "Privacy Policy",
      terms: "Terms & Conditions",
      email: "Email",
      disclaimer: "Marques Advisory & Investments coordinates residence pathways and selected investment opportunities with qualified independent professionals. It does not guarantee immigration approval, investment performance or tax outcomes.",
    },
  },
  es: {
    nav: {
      program: "Programa",
      costaRica: "Costa Rica",
      costaRicaDetail: "Programa de residencia",
      advisory: "Asesoría de residencia",
      investor: "Inversionista",
      pensioner: "Pensionado",
      rentier: "Rentista",
      investments: "Inversiones",
      experience: "La experiencia MA&I",
      consultation: "Consulta privada",
      menu: "Abrir menú",
    },
    landing: {
      eyebrow: "Marques Advisory & Investments",
      title: "Asesoría de residencia. Oportunidades en activos reales. Una plataforma en Costa Rica.",
      body: "Asesoramos a familias con movilidad global sobre las rutas de residencia en Costa Rica y estructuramos oportunidades seleccionadas de bienes raíces y activos reales.",
      choose: "Elija su próximo paso",
      advisoryLabel: "Advisory",
      advisoryTitle: "Conviértase en residente de Costa Rica",
      advisoryDetail: "Inversionista · Pensionado · Rentista",
      investmentsLabel: "Investments",
      investmentsTitle: "Explore oportunidades de inversión",
      investmentsDetail: "Bienes raíces · Activos reales estructurados",
    },
    hero: {
      eyebrow: "Programa de residencia en Costa Rica",
      title: "Conviértase en residente de Costa Rica.",
      body: "Una ruta privada y coordinada para inversionistas, pensionados y rentistas, desde la revisión del perfil hasta la ejecución local.",
      primary: "Explorar el programa",
      secondary: "Iniciar consulta privada",
      country: "Costa Rica",
      program: "Programa de residencia",
      note: "Un país. Tres rutas. Un Private Client Advisor.",
    },
    pathways: {
      kicker: "Encuentre su ruta",
      title: "Una decisión clara en treinta segundos.",
      intro: "Elija el perfil que mejor representa su situación actual. La evidencia y los requisitos gubernamentales se revisan de forma privada durante el proceso.",
      investor: {
        title: "Inversionista",
        body: "Para quienes ya poseen — o desean realizar — una inversión calificable en Costa Rica.",
        existing: "Ya realicé mi inversión",
        explore: "Explorar opciones de inversión",
      },
      pensioner: {
        title: "Pensionado",
        body: "Para quienes reciben una pensión vitalicia que cumple los requisitos aplicables.",
        action: "Revisar esta ruta",
      },
      rentier: {
        title: "Rentista",
        body: "Para quienes pueden demostrar ingresos estables y recurrentes que cumplen los requisitos aplicables.",
        action: "Revisar esta ruta",
      },
    },
    overview: {
      kicker: "Resumen del programa",
      title: "Costa Rica, coordinada alrededor de su familia.",
      body: "MA&I revisa su perfil, identifica la categoría de residencia adecuada y coordina la ejecución local con profesionales calificados. La aprobación siempre corresponde a la autoridad migratoria costarricense.",
      facts: [
        ["Rutas", "Inversionista · Pensionado · Rentista"],
        ["Servicio", "Coordinación privada de residencia"],
        ["Ejecución", "Una relación de asesoría dedicada"],
      ],
      factSheetTitle: "Fact Sheet de residencia en Costa Rica",
      factSheetBody: "Un resumen conciso de dos páginas, diseñado para revisar y compartir en privado con su familia.",
      download: "Descargar fact sheet",
      share: "Compartir por WhatsApp",
    },
    experience: {
      kicker: "Private Client Advisory",
      title: "La experiencia que hemos diseñado para brindar.",
      items: [
        "Me asignaron un Private Client Advisor que coordinó el proceso de principio a fin.",
        "Con la asesoría adecuada, el proceso se sintió claro, estructurado y manejable.",
      ],
      note: "Principios del servicio; no son testimonios de clientes.",
    },
    investments: {
      kicker: "Marques Investments",
      title: "¿Necesita invertir antes de aplicar?",
      body: "Las oportunidades seleccionadas de bienes raíces y otras inversiones se presentarán conforme completen la revisión interna de MA&I. Si ya posee un activo elegible, puede iniciar ahora con Residence Advisory.",
      status: "Oportunidades de inversión · Próximamente",
      detail: "Revisión privada disponible para necesidades de inversión relacionadas con residencia.",
      action: "Conversar sobre mi situación",
    },
    closing: {
      kicker: "Comience en privado",
      title: "El primer paso es una conversación confidencial.",
      body: "Cuéntenos dónde se encuentra hoy. Un Private Client Advisor le ayudará a identificar el siguiente paso adecuado.",
      action: "Iniciar consulta privada",
    },
    footer: {
      privacy: "Política de privacidad",
      terms: "Términos y condiciones",
      email: "Correo electrónico",
      disclaimer: "Marques Advisory & Investments coordina rutas de residencia y oportunidades de inversión seleccionadas con profesionales independientes calificados. No garantiza aprobaciones migratorias, rendimientos de inversión ni resultados fiscales.",
    },
  },
  fr: {
    nav: {
      program: "Programme",
      costaRica: "Costa Rica",
      costaRicaDetail: "Programme de résidence",
      advisory: "Conseil en résidence",
      investor: "Investisseur",
      pensioner: "Retraité",
      rentier: "Rentier",
      investments: "Investissements",
      experience: "L’expérience MA&I",
      consultation: "Consultation privée",
      menu: "Ouvrir le menu",
    },
    landing: {
      eyebrow: "Marques Advisory & Investments",
      title: "Conseil en résidence. Opportunités en actifs réels. Une plateforme au Costa Rica.",
      body: "Nous conseillons les familles internationales sur les parcours de résidence au Costa Rica et structurons des opportunités sélectionnées dans l’immobilier et les actifs réels.",
      choose: "Choisissez votre prochaine étape",
      advisoryLabel: "Conseil",
      advisoryTitle: "Devenez résident au Costa Rica",
      advisoryDetail: "Investisseur · Retraité · Rentier",
      investmentsLabel: "Investissements",
      investmentsTitle: "Explorer les opportunités d’investissement",
      investmentsDetail: "Immobilier · Actifs réels structurés",
    },
    hero: {
      eyebrow: "Programme de résidence au Costa Rica",
      title: "Devenez résident au Costa Rica.",
      body: "Un parcours privé et coordonné pour investisseurs, retraités et rentiers, de l’étude du profil à l’exécution locale.",
      primary: "Explorer le programme",
      secondary: "Commencer une consultation privée",
      country: "Costa Rica",
      program: "Programme de résidence",
      note: "Un pays. Trois parcours. Un conseiller privé dédié.",
    },
    pathways: {
      kicker: "Trouvez votre parcours",
      title: "Une décision claire en trente secondes.",
      intro: "Choisissez le profil qui correspond le mieux à votre situation. Les preuves et exigences gouvernementales sont examinées en privé pendant le processus.",
      investor: {
        title: "Investisseur",
        body: "Pour les candidats qui détiennent — ou envisagent de réaliser — un investissement admissible au Costa Rica.",
        existing: "J’ai déjà investi",
        explore: "Explorer les options d’investissement",
      },
      pensioner: {
        title: "Retraité",
        body: "Pour les candidats bénéficiant d’une pension viagère admissible.",
        action: "Examiner ce parcours",
      },
      rentier: {
        title: "Rentier",
        body: "Pour les candidats pouvant démontrer des revenus stables et récurrents admissibles.",
        action: "Examiner ce parcours",
      },
    },
    overview: {
      kicker: "Aperçu du programme",
      title: "Le Costa Rica, coordonné autour de votre famille.",
      body: "MA&I étudie votre profil, identifie la catégorie de résidence appropriée et coordonne l’exécution locale avec des professionnels qualifiés. L’approbation relève toujours de l’autorité migratoire costaricienne.",
      facts: [
        ["Parcours", "Investisseur · Retraité · Rentier"],
        ["Service", "Coordination privée de résidence"],
        ["Exécution", "Une relation de conseil dédiée"],
      ],
      factSheetTitle: "Fiche d’information — Résidence au Costa Rica",
      factSheetBody: "Une synthèse concise de deux pages, conçue pour être examinée et partagée en privé avec votre famille.",
      download: "Télécharger la fiche",
      share: "Partager sur WhatsApp",
    },
    experience: {
      kicker: "Private Client Advisory",
      title: "L’expérience que nous sommes conçus pour offrir.",
      items: [
        "Un conseiller privé m’a été attribué pour coordonner le processus du début à la fin.",
        "Avec le bon accompagnement, le processus est devenu clair, structuré et maîtrisable.",
      ],
      note: "Principes de service — il ne s’agit pas de témoignages clients.",
    },
    investments: {
      kicker: "Marques Investments",
      title: "Devez-vous investir avant de déposer votre demande ?",
      body: "Des opportunités immobilières et d’autres investissements sélectionnés seront présentés après examen interne par MA&I. Si vous possédez déjà un actif admissible, vous pouvez commencer dès maintenant avec Residence Advisory.",
      status: "Opportunités d’investissement · Bientôt disponibles",
      detail: "Examen privé disponible pour les besoins d’investissement liés à la résidence.",
      action: "Discuter de ma situation",
    },
    closing: {
      kicker: "Commencez en privé",
      title: "La première étape est une conversation confidentielle.",
      body: "Indiquez-nous votre situation actuelle. Un conseiller privé vous aidera à identifier la prochaine étape appropriée.",
      action: "Commencer une consultation privée",
    },
    footer: {
      privacy: "Politique de confidentialité",
      terms: "Conditions générales",
      email: "E-mail",
      disclaimer: "Marques Advisory & Investments coordonne des parcours de résidence et des opportunités d’investissement sélectionnées avec des professionnels indépendants qualifiés. La société ne garantit ni approbation migratoire, ni performance d’investissement, ni résultat fiscal.",
    },
  },
  zh: {
    nav: {
      program: "项目",
      costaRica: "哥斯达黎加",
      costaRicaDetail: "居留项目",
      advisory: "居留咨询",
      investor: "投资者",
      pensioner: "退休人士",
      rentier: "稳定收入人士",
      investments: "投资机会",
      experience: "MA&I 服务体验",
      consultation: "私人咨询",
      menu: "打开菜单",
    },
    landing: {
      eyebrow: "Marques Advisory & Investments",
      title: "居留咨询、实体资产机会，一站式连接哥斯达黎加。",
      body: "我们为具有全球流动需求的家庭提供哥斯达黎加居留路径咨询，并设计经筛选的房地产及实体资产机会。",
      choose: "选择您的下一步",
      advisoryLabel: "居留咨询",
      advisoryTitle: "成为哥斯达黎加居民",
      advisoryDetail: "投资者 · 退休人士 · 稳定收入人士",
      investmentsLabel: "投资",
      investmentsTitle: "探索投资机会",
      investmentsDetail: "房地产 · 结构化实体资产",
    },
    hero: {
      eyebrow: "哥斯达黎加居留项目",
      title: "成为哥斯达黎加居民。",
      body: "为投资者、退休人士和稳定收入人士提供私密且协调一致的路径，从背景评估到当地执行全程管理。",
      primary: "了解项目",
      secondary: "开始私人咨询",
      country: "哥斯达黎加",
      program: "居留项目",
      note: "一个国家，三条路径，一位专属私人客户顾问。",
    },
    pathways: {
      kicker: "选择适合您的路径",
      title: "三十秒内明确方向。",
      intro: "请选择最符合您当前情况的类别。相关证明和政府要求将在后续流程中进行私密审核。",
      investor: {
        title: "投资者",
        body: "适用于已在哥斯达黎加持有或计划进行符合条件投资的申请人。",
        existing: "我已经完成投资",
        explore: "了解投资选择",
      },
      pensioner: {
        title: "退休人士",
        body: "适用于领取符合条件的终身养老金的申请人。",
        action: "了解此路径",
      },
      rentier: {
        title: "稳定收入人士",
        body: "适用于能够证明符合条件的稳定持续收入的申请人。",
        action: "了解此路径",
      },
    },
    overview: {
      kicker: "项目概览",
      title: "以您的家庭为中心，协调哥斯达黎加居留规划。",
      body: "MA&I 将评估您的情况、识别合适的居留类别，并与合资格专业人士协调当地执行。最终批准权始终属于哥斯达黎加移民主管机关。",
      facts: [
        ["申请路径", "投资者 · 退休人士 · 稳定收入人士"],
        ["服务", "私人居留协调"],
        ["执行", "专属顾问全程协调"],
      ],
      factSheetTitle: "哥斯达黎加居留项目概览",
      factSheetBody: "两页精要资料，方便您与家人私下阅读和分享。",
      download: "下载项目概览",
      share: "通过 WhatsApp 分享",
    },
    experience: {
      kicker: "私人客户咨询",
      title: "我们致力于提供的服务体验。",
      items: [
        "我获得了一位专属私人客户顾问，从开始到结束协调整个流程。",
        "在专业指导下，整个流程清晰、有序且易于推进。",
      ],
      note: "以上为服务原则，并非客户评价。",
    },
    investments: {
      kicker: "Marques Investments",
      title: "申请前需要完成投资？",
      body: "经过 MA&I 内部审核的精选房地产及其他投资机会将陆续推出。如果您已持有符合条件的资产，现在即可开始居留咨询。",
      status: "投资机会 · 即将推出",
      detail: "可为与居留相关的投资需求安排私人评估。",
      action: "讨论我的情况",
    },
    closing: {
      kicker: "私密开启",
      title: "第一步是一场保密沟通。",
      body: "请告诉我们您目前的情况。私人客户顾问将协助您确定合适的下一步。",
      action: "开始私人咨询",
    },
    footer: {
      privacy: "隐私政策",
      terms: "条款与条件",
      email: "电子邮件",
      disclaimer: "Marques Advisory & Investments 与合资格的独立专业人士共同协调居留路径及精选投资机会，不保证移民批准、投资表现或税务结果。",
    },
  },
} as const
