// Page-scoped editorial copy; shared navigation and language resolution remain unchanged.
export const frameworkCopy: Record<string, readonly [string, string, string]> = {
  "Pause framework motion": ["Pausar el movimiento del marco", "Mettre le défilement en pause", "暂停框架滚动"],
  "Resume framework motion": ["Reanudar el movimiento del marco", "Reprendre le défilement", "继续框架滚动"],
  "How Marqués Evaluates Real Asset Opportunities": ["Cómo evalúa Marqués las oportunidades en activos reales", "Comment Marqués évalue les opportunités en actifs réels", "Marqués 如何评估实物资产机会"],
  "Structured for capital. Built for execution.": ["Estructurados para el capital. Concebidos para la ejecución.", "Structurés pour le capital. Conçus pour l’exécution.", "为资本构建架构，为执行奠定基础。"],
  "We evaluate, structure and prepare real asset opportunities for disciplined investment and execution.": ["Evaluamos, estructuramos y preparamos oportunidades en activos reales para una inversión y ejecución disciplinadas.", "Nous évaluons, structurons et préparons les opportunités en actifs réels pour un investissement et une exécution rigoureux.", "我们评估、构建并准备实物资产机会，以支持审慎投资与有序执行。"],
  "The Marqués Review Framework": ["El marco de evaluación de Marqués", "Le cadre d’analyse Marqués", "Marqués 审查框架"],
  "From asset clarity to institutional readiness.": ["De la claridad del activo a la preparación institucional.", "De la compréhension de l’actif à la préparation institutionnelle.", "从资产明晰到机构准备。"],
  "We begin with the asset.": ["Comenzamos por el activo.", "Nous commençons par l’actif.", "始于资产。"],
  "Then we define the structure.": ["Luego definimos la estructura.", "Puis nous définissons la structure.", "继而明确架构。"],
  "Only then do we position the opportunity.": ["Solo entonces posicionamos la oportunidad.", "C’est alors que nous positionnons l’opportunité.", "而后定位机会。"],
  "Location": ["Ubicación", "Emplacement", "区位"],
  "Logic": ["Lógica", "Logique", "逻辑"],
  "Potential": ["Potencial", "Potentiel", "潜力"],
  "Readiness": ["Preparación", "Préparation", "准备"],
  "Alignment": ["Alineación", "Convergence", "契合"],
  "Asset": ["Activo", "Actif", "资产"],
  "Thesis": ["Tesis", "Thèse", "投资逻辑"],
  "Structure": ["Estructura", "Structure", "架构"],
  "Capital": ["Capital", "Capital", "资本"],
  "Execution": ["Ejecución", "Exécution", "执行"],
  "Monetization": ["Monetización", "Monétisation", "价值实现"],
  "Real Asset Review": ["Evaluación de activos reales", "Analyse d’actifs réels", "实物资产审查"],
  "Asset Categories": ["Categorías de activos", "Catégories d’actifs", "资产类别"],
  "From opportunity to institutional readiness.": ["De la oportunidad a la preparación institucional.", "De l’opportunité à la préparation institutionnelle.", "从机会到机构准备。"],
  "A private conversation about real assets, structuring and execution in Costa Rica.": ["Una conversación privada sobre activos reales, estructuración y ejecución en Costa Rica.", "Un échange privé sur les actifs réels, la structuration et l’exécution au Costa Rica.", "围绕哥斯达黎加实物资产、架构设计与执行的私人交流。"],
  "Discuss an Opportunity": ["Conversemos sobre una oportunidad", "Échanger sur une opportunité", "探讨机会"],
  "Contemporary architecture with natural light, timber and stone": ["Arquitectura contemporánea con luz natural, madera y piedra", "Architecture contemporaine, lumière naturelle, bois et pierre", "融入自然光、木材与石材的当代建筑"],
}
