import Link from "next/link"
import { ArrowRight } from "lucide-react"
import { CtaBand, LegalNote, PageIntro, SectionHeading, SiteFrame } from "@/components/editorial-shell"
import { siteConfig } from "@/lib/site"
import { FactSheetGate } from "@/components/fact-sheet-gate"

export default function ResidencyPage() {
  return <SiteFrame><PageIntro eyebrow="Costa Rica · Residence by Investment" title="Become a Resident in Costa Rica."><p>Residence by investment and other pathways for a global life.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/contact" className="bg-primary px-5 py-3 text-[10px] font-bold uppercase tracking-[0.15em] text-primary-foreground">Enquire</Link><FactSheetGate /></div></PageIntro><main><section className="mx-auto max-w-7xl px-5 py-14 md:px-8"><div className="grid gap-8 border-y border-border py-8 md:grid-cols-3"><div><p className="text-[10px] uppercase tracking-[0.18em] text-accent">Investment</p><p className="mt-3 font-serif text-3xl text-primary">From US$150,000</p></div><div><p className="text-[10px] uppercase tracking-[0.18em] text-accent">Program</p><p className="mt-3 text-sm leading-6 text-muted-foreground">Temporary residence, renewable subject to applicable requirements and approval.</p></div><div><p className="text-[10px] uppercase tracking-[0.18em] text-accent">Dependents</p><p className="mt-3 text-sm leading-6 text-muted-foreground">Eligible dependents may be included, subject to applicable requirements.</p></div></div></section><section className="mx-auto max-w-7xl px-5 pb-20 md:px-8"><SectionHeading eyebrow="Pathways" title="Three pathways. One clear process."/><div className="mt-10 grid gap-5 md:grid-cols-3">{siteConfig.residency.pathways.map((p, i) => <article key={p.id} className="border-t-2 border-primary pt-5"><p className="font-mono text-xs text-accent">0{i+1}</p><h2 className="mt-5 font-serif text-3xl text-primary">{p.name}</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">{p.description}</p><p className="mt-7 text-xs font-bold uppercase tracking-[0.12em] text-primary">{p.minAmountUSD}</p></article>)}</div></section><section className="border-y border-border bg-secondary"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 md:grid-cols-[0.8fr_1.2fr] md:px-8"><SectionHeading eyebrow="Our process" title="Clarity at every stage."/><ol className="grid gap-5">{["Evaluation — profile, family and goals.","Pathway — applicable category and structure.","Coordination — local execution of the application.","Continuity — DIMEX, renewal and long-term planning."].map((item, i) => <li key={item} className="flex gap-4 border-t border-border pt-4 text-sm leading-6 text-primary"><span className="font-mono text-xs text-accent">0{i+1}</span>{item}</li>)}</ol></div></section><div className="mx-auto max-w-7xl px-5 py-10 md:px-8"><LegalNote>{siteConfig.legalDisclaimer.residency}</LegalNote></div></main><CtaBand title="Start with an eligibility conversation." href="/contact"/></SiteFrame>
}
